# Generated by Django 5.0.1 on 2024-01-24 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='days_running',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='poll',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
